
include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Calculator

Calculator_HEADERS =  CalcFace.h CalcBrain.h

Calculator_OBJC_FILES = main.m  CalcFace.m CalcBrain.m

Calculator_RESOURCE_FILES = Calculator.app.tiff

include $(GNUSTEP_MAKEFILES)/application.make
