include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Calculator

Calculator_OBJC_FILES = main.m CalcFace.m CalcBrain.m

Calculator_HARDERS = CalcFace.h CalcBrain.h
#关联资源文件
Calculator_RESOURCE_FILES = Calculator.app.tiff

include $(GNUSTEP_MAKEFILES)/application.make
