
include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Calculator
Calculator_HEADERS = CalcBrain.h CalcFace.h
Calculator_OBJC_FILES = main.m CalcBrain.m CalcFace.m
Calculator_RESOURCE_FILES = Calculator.app.tiff

include $(GNUSTEP_MAKEFILES)/application.make


